import { WorldMap } from './WorldMap';
import type { InteractableTarget } from './playerController';
import { sanctuaryFor } from './sanctuaries';
import type { CampaignState } from '../game/types';
import type { AdventureWorldMarker } from './adventureMarkers';

export interface WorldwalkerPanelProps {
  state: CampaignState; facing: 'front' | 'back' | 'left' | 'right'; travelling: boolean; travelFrom: string | null; mark: { xp: number; territoryId: string; key: number } | null; reachable: string[];
  isImpact: boolean; arrivalNotice: { territoryId: string; label: string; sanctuary: string; glyph: string } | null; activeInterior: string | null; activeWaystone: { id: string; label: string; inscription?: string } | null;
  talking: boolean; hasEncounter: boolean; encounterLabel: string; menuOpen: boolean; screenIsWorld: boolean; isOffline: boolean; xpCurrent: number; xpRequired: number; atMaxLevel: boolean; xpPercent: number; activeTerritoryLabel: string; adventureMarkers: readonly AdventureWorldMarker[];
  onSelectRegion: (territoryId: string) => void; onPositionSettled: (position: { x: number; y: number; territoryId: string }) => void; onInteract: (target: InteractableTarget | null) => void; onInteriorChange: (id: string | null) => void; onOpenMenu: () => void; onEnter: () => void; onResumeEncounter: () => void; onDismissWaystone: () => void;
}

export function WorldwalkerPanel({ state, facing, travelling, travelFrom, mark, reachable, isImpact, arrivalNotice, activeInterior, activeWaystone, talking, hasEncounter, encounterLabel, menuOpen, screenIsWorld, isOffline, xpCurrent, xpRequired, atMaxLevel, xpPercent, activeTerritoryLabel, adventureMarkers, onSelectRegion, onPositionSettled, onInteract, onInteriorChange, onOpenMenu, onEnter, onResumeEncounter, onDismissWaystone }: WorldwalkerPanelProps) {
  return <section className={`stage${isImpact ? ' is-impact' : ''}`} data-testid="world-stage">
    {arrivalNotice && <div className="region-arrival-card" data-testid="region-arrival-card" role="status" aria-live="polite"><span className="region-arrival-glyph" aria-hidden="true">{arrivalNotice.glyph}</span><div className="region-arrival-text"><span className="region-arrival-eyebrow">Now Entering</span><h3 className="region-arrival-title">{arrivalNotice.label}</h3><p className="region-arrival-sanctuary">{arrivalNotice.sanctuary}</p></div></div>}
    <WorldMap state={state} facing={facing} travelling={travelling} travelFrom={travelFrom} mark={mark} reachable={reachable} adventureMarkers={adventureMarkers} reducedMotion={state.settings.reducedMotion} onSelectRegion={onSelectRegion} onPositionSettled={onPositionSettled} onInteract={onInteract} controlsDisabled={talking || hasEncounter || menuOpen || !screenIsWorld || Boolean(activeWaystone)} activeInterior={activeInterior} onInteriorChange={onInteriorChange} />
    <div className="hud" data-testid="hud"><div className="hud-place"><strong data-testid="hud-territory">{activeInterior ? sanctuaryFor(activeInterior).name : activeTerritoryLabel}</strong><span className="hud-progress" data-testid="hud-progress" data-xp={state.xp} data-level={state.level} aria-label={`Level ${state.level}, ${xpCurrent} of ${xpRequired} to the next level`}><i data-testid="hud-level">L{state.level}</i><span className="hud-track"><b style={{ width: `${atMaxLevel ? 100 : xpPercent}%` }} /></span></span></div><button className="hud-menu" data-testid="open-menu" aria-label="Open menu" aria-haspopup="dialog" aria-expanded={menuOpen} onClick={onOpenMenu}><span aria-hidden="true">☰</span></button>{isOffline && <span className="chip offline" data-testid="offline-indicator">Offline</span>}</div>
    {!talking && !hasEncounter && <button className="world-enter" data-testid="enter-encounter" onClick={onEnter}><span>{activeInterior ? 'Consult Cartographer' : 'Open Journal'}</span></button>}{!talking && hasEncounter && <button className="world-enter" data-testid="resume-encounter" onClick={onResumeEncounter}><span>Resume {encounterLabel}</span></button>}
    {activeWaystone && <div className="waystone-overlay" data-testid="waystone-overlay" role="dialog" aria-label={activeWaystone.label}><div className="waystone-card"><p className="waystone-eyebrow">Trail Marker</p><h3 className="waystone-title">{activeWaystone.label}</h3><p className="waystone-text">{activeWaystone.inscription}</p><button type="button" className="primary waystone-dismiss" data-testid="waystone-dismiss" onClick={onDismissWaystone}>Continue Journey</button></div></div>}
  </section>;
}
